services:
  db:
    container_name: server_db
    image: 'linuxserver/mariadb:10.5.13'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Chismosear01 #Cambiar password si se desea
      - MYSQL_DATABASE=db_server
      - MYSQL_USER=server #Cambiar usuario si se desea
      - MYSQL_PASSWORD=server #Cambiar password si se desea
    restart: always

  backendserver:
    container_name: SERVERAPI
    build: ./serverAPI/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_server
      - SPRING_DATASOURCE_USERNAME=server #Usar mismo usuario que la base de datos
      - SPRING_DATASOURCE_PASSWORD=server #Usar misma contraseña que la base de datos
      - CLIENT_URL=http://localhost

    ports:
      - "8080:8080"
    links:
      - "db"
    depends_on:
      - "db"
    restart: always

  frontend:
    container_name: server_frontend
    build:
      context: ./server_frontend/
      args:
        - apiURL=http://localhost:8080
    ports:
      - "80:80"
    restart: always

  phpmyadmin:
    container_name: server_dbadmin
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    restart: always